# Generated by Django 4.2.7 on 2023-11-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desciption',
            new_name='description',
        ),
    ]
